<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);GetTfmPublishedFiles</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>MigrationHelper.PluginBase</PackageId>
	<RootNamespace>MigrationHelper.PluginBase</RootNamespace>
    <PackageOutputPath>bin\outputPackages</PackageOutputPath>
    <PackageTags>plugin</PackageTags>
    <Authors>Placeholder</Authors>
    <Description>
			Placeholder
		</Description>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.ServiceModel" />
    <PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.14.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.*" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
  <Target Name="GetTfmPublishedFiles">
    <Message Text="GetTfmPublishedFiles from: $(OutputPath)" />
    <ItemGroup>
      <BuildOutputInPackage Include="$(OutputPath)\*.*" Exclude="$(OutputPath)\microsoft.*rm.sdk*" />
    </ItemGroup>
  </Target>
</Project>